apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp-devstream-demo001
  labels:
    app: go-webapp-devstream-demo001
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: go-webapp-devstream-demo001
  template:
    metadata:
      labels:
        app: go-webapp-devstream-demo001
    spec:
      containers:
      - name: go-webapp-devstream-demo001
        image: "YOUR_DOCKER/go-webapp-devstream-demo:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 8080
